#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
from pathlib import Path

from tools.ai.core import enabled_platform_ids, load_model
from tools.ai.validate import (
    collect_drift,
    collect_ownership_errors,
    instantiate_plugins,
    output_for_path,
    output_inventory,
    render_all,
)


REPO_ROOT = Path(__file__).resolve().parents[2]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="scripts/ai",
        description="Compile ai/** source instructions into native AI tool files.",
    )
    subparsers = parser.add_subparsers(dest="command")

    subparsers.add_parser("validate", help="validate source, outputs, and ownership")

    generate_parser = subparsers.add_parser("generate", help="write generated outputs")
    generate_parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed generated outputs differ",
    )

    subparsers.add_parser("list", help="list generated platform outputs")

    explain_parser = subparsers.add_parser("explain", help="explain generated output provenance")
    explain_parser.add_argument("path", help="generated file or generated directory path")

    args = parser.parse_args(argv)
    if args.command is None:
        parser.print_help()
        return 0

    model = load_model(REPO_ROOT)
    plugins, plugin_errors = instantiate_plugins(model)
    if plugin_errors:
        _print_errors(plugin_errors)
        return 1

    if args.command == "validate":
        return _validate(model, plugins)
    if args.command == "generate":
        return _generate(model, plugins, check=args.check)
    if args.command == "list":
        return _list(model, plugins)
    if args.command == "explain":
        return _explain(model, plugins, Path(args.path))

    parser.print_help()
    return 1


def _validate(model, plugins) -> int:
    outputs, errors = render_all(model, plugins)
    if not errors:
        errors.extend(collect_ownership_errors(model, outputs))
    if errors:
        _print_errors(errors)
        return 1

    print("ok: source files valid")
    print("ok: platform configs valid")
    print("ok: skills valid")
    print("ok: generated ownership valid")
    return 0


def _generate(model, plugins, *, check: bool) -> int:
    outputs, errors = render_all(model, plugins)
    if errors:
        _print_errors(errors)
        return 1

    if check:
        stale, extra = collect_drift(model, outputs)
        if stale or extra:
            for path in stale:
                print(f"stale: {path}")
            for path in extra:
                print(f"extra: {path}")
            print()
            print("Run:")
            print("  scripts/ai generate")
            return 1
        print("ok: generated outputs are up to date")
        return 0

    for output in sorted(outputs, key=lambda item: item.path.as_posix()):
        path = model.repo_root / output.path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(output.content, encoding="utf-8", newline="\n")
        print(f"wrote {output.path.as_posix()}")
    return 0


def _list(model, plugins) -> int:
    outputs, errors = render_all(model, plugins)
    if errors:
        _print_errors(errors)
        return 1
    inventory = output_inventory(outputs)
    for platform_id in enabled_platform_ids(model):
        print(platform_id)
        for target, output in sorted(
            inventory.get(platform_id, {}).items(),
            key=lambda item: item[0].as_posix(),
        ):
            print(f"  {target.as_posix()}")
            for source in output.source_ids:
                print(f"    <- {source}")
        if not inventory.get(platform_id):
            print("  (no generated outputs)")
    return 0


def _explain(model, plugins, target: Path) -> int:
    outputs, errors = render_all(model, plugins)
    if errors:
        _print_errors(errors)
        return 1
    normalized = _normalize_cli_path(target)
    output = output_for_path(outputs, normalized)
    if output is None:
        print(f"error: {target.as_posix()} is not generated by scripts/ai")
        return 1

    print("Target:")
    print(f"  {output.logical_target.as_posix()}")
    if output.path != output.logical_target:
        print("File:")
        print(f"  {output.path.as_posix()}")
    print()
    print("Platform:")
    print(f"  {output.platform}")
    print()
    print("Sources:")
    for source in output.source_ids:
        print(f"  {source}")

    max_chars = output.limits.get("max_chars")
    if max_chars:
        print()
        print("Limits:")
        print(f"  max_chars: {max_chars}")
        print(f"  actual_chars: {len(output.content)}")

    actual_path = model.repo_root / output.path
    print()
    print("Validation:")
    if actual_path.exists() and actual_path.read_text() == output.content:
        print("  ok")
    elif not actual_path.exists():
        print("  missing")
    else:
        print("  stale")
    return 0


def _normalize_cli_path(path: Path) -> Path:
    if path.is_absolute():
        try:
            return path.resolve().relative_to(REPO_ROOT)
        except ValueError:
            return path
    return Path(os.fspath(path))


def _print_errors(errors: list[str]) -> None:
    for error in errors:
        print(error)
