from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from tools.ai.core import fragment_sources, render_included_fragments, repo_relative
from tools.ai.model import GeneratedFile, Skill, SourceModel, TargetOutput
from tools.ai.yaml_util import dump_yaml


TRACE_TEXT = "Generated by scripts/ai."


def markdown_trace(platform: str, target: Path, sources: tuple[str, ...]) -> str:
    lines = [
        "<!--",
        TRACE_TEXT,
        "Do not edit directly.",
        "",
        f"Platform: {platform}",
        f"Target: {target.as_posix()}",
        "Sources:",
    ]
    lines.extend(f"  - {source}" for source in sources)
    lines.append("-->")
    return "\n".join(lines) + "\n"


def yaml_comment_trace(platform: str, target: Path, sources: tuple[str, ...]) -> str:
    lines = [
        f"# {TRACE_TEXT}",
        "# Do not edit directly.",
        "#",
        f"# Platform: {platform}",
        f"# Target: {target.as_posix()}",
        "# Sources:",
    ]
    lines.extend(f"#   - {source}" for source in sources)
    return "\n".join(lines) + "\n"


def render_markdown_output(
    model: SourceModel,
    output: TargetOutput,
    *,
    platform: str,
    frontmatter: dict[str, Any] | None = None,
    imports: list[str] | None = None,
) -> GeneratedFile:
    sources = fragment_sources(model, output)
    title = output.title or output.id
    body_parts: list[str] = []
    if frontmatter is not None:
        body_parts.append("---\n" + dump_yaml(frontmatter).rstrip() + "\n---\n")
    body_parts.append(markdown_trace(platform, output.path, sources))
    if imports:
        body_parts.extend(f"@{path}\n" for path in imports)
        body_parts.append("")
    body_parts.append(f"# {title}\n")
    body_parts.append(render_included_fragments(model, output))
    return GeneratedFile(
        path=output.path,
        content="\n\n".join(part.strip("\n") for part in body_parts if part.strip()) + "\n",
        platform=platform,
        source_ids=sources,
        logical_target=output.path,
        limits=output.limits,
    )


def render_skill_files(
    model: SourceModel,
    skill: Skill,
    *,
    platform: str,
    target_dir: Path,
    include_openai_metadata: bool,
    include_claude_metadata: bool,
) -> list[GeneratedFile]:
    sources = skill_sources(model, skill)
    files: list[GeneratedFile] = []

    frontmatter: dict[str, Any] = {
        "name": skill.name,
        "description": skill.description,
    }
    extra_frontmatter = skill.metadata.get("frontmatter", {})
    if isinstance(extra_frontmatter, dict):
        frontmatter.update(extra_frontmatter)
    if include_claude_metadata:
        claude = skill.metadata.get("claude", {})
        if isinstance(claude, dict) and claude.get("allowed_tools"):
            frontmatter["allowed-tools"] = claude["allowed_tools"]

    instructions = skill.instructions_path.read_text() if skill.instructions_path.exists() else ""
    skill_path = target_dir / "SKILL.md"
    skill_content = (
        "---\n"
        + dump_yaml(frontmatter).rstrip()
        + "\n---\n"
        + markdown_trace(platform, skill_path, sources)
        + "\n"
        + instructions.strip()
        + "\n"
    )
    files.append(
        GeneratedFile(
            path=skill_path,
            content=skill_content,
            platform=platform,
            source_ids=sources,
            logical_target=target_dir,
        )
    )

    for resource_path in [*skill.reference_paths, *skill.script_paths]:
        relative_reference = resource_path.relative_to(skill.path)
        target_path = target_dir / relative_reference
        content = resource_path.read_text() if resource_path.exists() else ""
        files.append(
            GeneratedFile(
                path=target_path,
                content=resource_trace_content(
                    platform,
                    target_path,
                    sources,
                    content,
                ),
                platform=platform,
                source_ids=sources,
                logical_target=target_dir,
            )
        )

    if include_openai_metadata:
        openai = skill.metadata.get("openai", {})
        interface = {
            "interface": {
                "display_name": openai.get("display_name", "") if isinstance(openai, dict) else "",
                "short_description": (
                    openai.get("short_description", "") if isinstance(openai, dict) else ""
                ),
                "default_prompt": (
                    openai.get("default_prompt", "") if isinstance(openai, dict) else ""
                ),
            }
        }
        openai_path = target_dir / "agents" / "openai.yaml"
        files.append(
            GeneratedFile(
                path=openai_path,
                content=yaml_comment_trace(platform, openai_path, sources)
                + dump_yaml(interface),
                platform=platform,
                source_ids=sources,
                logical_target=target_dir,
            )
        )

    manifest_path = target_dir / ".ai-manifest.json"
    generated_files = sorted(
        path.relative_to(target_dir).as_posix()
        for path in [file.path for file in files] + [manifest_path]
    )
    manifest = {
        "generated_by": "scripts/ai",
        "platform": platform,
        "target": target_dir.as_posix(),
        "sources": list(sources),
        "files": generated_files,
    }
    files.append(
        GeneratedFile(
            path=manifest_path,
            content=json.dumps(manifest, indent=2, sort_keys=False) + "\n",
            platform=platform,
            source_ids=sources,
            logical_target=target_dir,
        )
    )
    return files


def skill_sources(model: SourceModel, skill: Skill) -> tuple[str, ...]:
    sources = [
        repo_relative(model.repo_root, skill.path / "skill.yml"),
        repo_relative(model.repo_root, skill.instructions_path),
    ]
    sources.extend(repo_relative(model.repo_root, path) for path in skill.reference_paths)
    sources.extend(repo_relative(model.repo_root, path) for path in skill.script_paths)
    return tuple(sources)


def resource_trace_content(
    platform: str,
    target_path: Path,
    sources: tuple[str, ...],
    content: str,
) -> str:
    if target_path.suffix in {".md", ".mdc"}:
        return markdown_trace(platform, target_path, sources) + "\n" + content.strip() + "\n"
    if target_path.suffix in {".yaml", ".yml"}:
        return yaml_comment_trace(platform, target_path, sources) + content.strip() + "\n"

    trace = line_comment_trace(platform, target_path, sources)
    if content.startswith("#!"):
        first_line, _, rest = content.partition("\n")
        return first_line.rstrip() + "\n" + trace + rest.strip() + "\n"
    return trace + content.strip() + "\n"


def line_comment_trace(platform: str, target: Path, sources: tuple[str, ...]) -> str:
    lines = [
        f"// {TRACE_TEXT}",
        "// Do not edit directly.",
        "//",
        f"// Platform: {platform}",
        f"// Target: {target.as_posix()}",
        "// Sources:",
    ]
    lines.extend(f"//   - {source}" for source in sources)
    return "\n".join(lines) + "\n"
